server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: MovieService
          uri: lb://MovieService
          predicates:
            - Path=/movies/**

        - id: RecommendationService
          uri: lb://RecommendationService
          predicates:
            - Path=/recommendation/**
